name: CI-TEST
# Events
on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest # GitHub Hosted Runner (windows-latest, macos-latest)

    steps: # Steps can contain run commands or actions
      - uses: actions/checkout@v3 # Standard Action

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
